# Generated by Django 4.2 on 2023-05-26 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribers',
        ),
    ]
